create database BD_BDM;

USE BD_BDM;

SELECT * FROM sysobjects
where xtype='U';

DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
	ID_USUARIO				tinyint auto_increment		NOT NULL,
	NOMBRES					varchar(50)					NOT NULL,
    APELLIDOS				VARCHAR(50)					NOT NULL,
	GENERO					VARCHAR(10)					NOT NULL,
	FECHA_NACIMIENTO		DATE						NOT NULL,
	EMAIL					VARCHAR(50)					NOT NULL,
	CONTRASENA				VARCHAR(20)					NOT NULL,
	FECHA_REGISTRO			DATE						NOT NULL,
    ULTIMA_MODIFICACION		DATE						NOT NULL,
    IMAGEN					mediumblob					NULL,

	CONSTRAINT PK_USUARIO
			PRIMARY KEY (ID_USUARIO)
);

DROP TABLE IF EXISTS INSTRUCTOR;

CREATE TABLE INSTRUCTOR (
	ID_INSTRUCTOR			tinyint auto_increment		NOT NULL,
	USUARIO					tinyint 					NOT NULL,

	CONSTRAINT PK_INSTRUCTOR
			PRIMARY KEY (ID_INSTRUCTOR),
	CONSTRAINT FK_INSTRUCTOR_USUARIO
			FOREIGN KEY (USUARIO)
			REFERENCES USUARIO(ID_USUARIO)
);

DROP TABLE IF EXISTS ESTUDIANTE;

CREATE TABLE ESTUDIANTE (
	ID_ESTUDIANTE			tinyint auto_increment		NOT NULL,
	USUARIO					tinyint 					NOT NULL,

	CONSTRAINT PK_ESTUDIANTE
			PRIMARY KEY (ID_ESTUDIANTE),
	CONSTRAINT FK_ESTUDIANTE_USUARIO
			FOREIGN KEY (USUARIO)
			REFERENCES USUARIO(ID_USUARIO)
);

DROP TABLE IF EXISTS CURSO_INSTRUCTOR;

CREATE TABLE CURSO_INSTRUCTOR (
	ID_CURSO_INSTRUCTOR			tinyint auto_increment		NOT NULL,
	INSTRUCTOR  				tinyint						NOT NULL,
    NOMBRE						VARCHAR(100)				NOT NULL,
    COSTO						float						NOT NULL,
    DESCRIPCION					VARCHAR(300)				NOT NULL,
    IMAGEN						mediumblob				 	NULL,

	CONSTRAINT PK_CURSO_INSTRUCTOR
			PRIMARY KEY (ID_CURSO_INSTRUCTOR),
	CONSTRAINT FK_CURSO_INSTRUCTOR_CREADOR
			FOREIGN KEY (INSTRUCTOR)
			REFERENCES INSTRUCTOR(ID_INSTRUCTOR)
);

DROP TABLE IF EXISTS NIVEL_INSTRUCTOR;

CREATE TABLE NIVEL_INSTRUCTOR (
	ID_NIVEL					tinyint auto_increment	not null,
    NOMBRE						VARCHAR(100)			NOT NULL,
    CONTENIDO_ADICIONAL			blob					null,
    CURSO						tinyint					NOT NULL,

	CONSTRAINT PK_NIVEL_INSTRUCTOR
			PRIMARY KEY (ID_NIVEL),
	CONSTRAINT FK_CURSO_NIVEL_INSTRUCTOR
			FOREIGN KEY (CURSO)
			REFERENCES CURSO_INSTRUCTOR(ID_CURSO_INSTRUCTOR)
);

DROP TABLE IF EXISTS SUBNIVEL_INSTRUCTOR;

CREATE TABLE SUBNIVEL_INSTRUCTOR (
	ID_SUBNIVEL					tinyint auto_increment	NOT NULL,
    TITULO						VARCHAR(50)				NOT NULL,
    DESCRIPCION					VARCHAR(300)			NOT NULL,
    VIDEO						blob					NOT NULL,
    NIVEL						tinyint					NOT NULL,
	CONTENIDO_ADICIONAL			blob					NULL,

	CONSTRAINT PK_SUBNIVEL_INSTRUCTOR
			PRIMARY KEY (ID_SUBNIVEL),
	CONSTRAINT FK_CURSO_NIVEL_SUBNIVEL_INSTRUCTOR
			FOREIGN KEY (NIVEL)
			REFERENCES NIVEL_INSTRUCTOR(ID_NIVEL)
);

DROP TABLE IF EXISTS CURSO_ALUMNO;

CREATE TABLE CURSO_ALUMNO (
	ID_CURSO_ALUMNO			tinyint auto_increment	NOT NULL,
	ALUMNO  				tinyint					NOT NULL,
    CURSO					tinyint					NOT NULL,
    PROGRESO				FLOAT					NOT NULL,
    FECHA_INSCRIPCION		DATE					NOT NULL,
    FECHA_FINALIZACION		DATE					NOT NULL,
    ESTATUS					BOOL					NOT NULL,
	FORMA_PAGO				VARCHAR(30)				NOT NULL,

	CONSTRAINT ID_CURSO_ALUMNO
			PRIMARY KEY (ID_CURSO_ALUMNO),
	CONSTRAINT FK_ID_CURSO_ALUMNO_CURSO
			FOREIGN KEY (CURSO)
            REFERENCES CURSO_INSTRUCTOR(ID_CURSO_INSTRUCTOR),
	CONSTRAINT FK_CURSO_ALUMNO_ESTUDIANTE
			FOREIGN KEY (ALUMNO)
            REFERENCES ESTUDIANTE(ID_ESTUDIANTE)
);

DROP TABLE IF EXISTS NIVEL_ALUMNO;

CREATE TABLE NIVEL_ALUMNO (
	ID_NIVEL_ALUMNO				tinyint		auto_increment		NOT NULL,
    ESTATUS						BOOL							NOT NULL,
    CURSO						tinyint							NOT NULL,

	CONSTRAINT PK_NIVEL_ALUMNO
			PRIMARY KEY (ID_NIVEL_ALUMNO),
	CONSTRAINT FK_NIVEL_ALUMNO_CURSO
			FOREIGN KEY (CURSO)
			REFERENCES CURSO_ALUMNO(ID_CURSO_ALUMNO)
);

DROP TABLE IF EXISTS SUBNIVEL_ALUMNO;

CREATE TABLE SUBNIVEL_ALUMNO (
	ID_SUBNIVEL_ALUMNO			tinyint auto_increment				NOT NULL,
    ESTATUS						BOOL								NOT NULL,
    NIVEL						tinyint						NOT NULL,

	CONSTRAINT PK_SUBNIVEL_ALUMNO
			PRIMARY KEY (ID_SUBNIVEL_ALUMNO),
	CONSTRAINT FK_NIVEL_SUBNIVEL_ALUMNO_NIVEL
			FOREIGN KEY (NIVEL)
			REFERENCES NIVEL_ALUMNO(ID_NIVEL_ALUMNO)
);

DROP TABLE IF EXISTS COMENTARIOS;

CREATE TABLE COMENTARIOS (
	ID_COMENTARIOS				tinyint	auto_increment	NOT NULL,
    FECHA_CREACION				DATE			NOT NULL,
    HORA_CREACION				datetime		NOT NULL,
    ALUMNO						tinyint 		NOT NULL,
    CALIFICACION				tinyint 		NOT NULL,
    CURSO						tinyint 		NOT NULL,

	CONSTRAINT PK_COMENTARIOS
			PRIMARY KEY (ID_COMENTARIOS),
	CONSTRAINT FK_COMENTARIOS_ESTUDIANTE
			FOREIGN KEY (ALUMNO)
            REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
	CONSTRAINT FK_COMENTARIOS_CURSO
			FOREIGN KEY (CURSO)
			REFERENCES CURSO_ALUMNO(ID_CURSO_ALUMNO)
);

DROP TABLE IF EXISTS CHAT_ALUMNO_PROFESOR;

CREATE TABLE CHAT_ALUMNO_PROFESOR (
	ID_ALUM_PROF			tinyint				NOT NULL,
    ID_CURSO_ALUM			tinyint				NOT NULL,

	CONSTRAINT PK_CHAT_ALUM_PROF
			PRIMARY KEY (ID_ALUM_PROF),
	CONSTRAINT FK_CHAT_CURSO_ALUM
			FOREIGN KEY (ID_CURSO_ALUM)
			REFERENCES CURSO_ALUMNO(ID_CURSO_ALUMNO)
);

DROP TABLE IF EXISTS CHAT_USUARIOS;

CREATE TABLE CHAT_USUARIOS (
	ID_CHAT			tinyint				NOT NULL,

	CONSTRAINT PK_CHAT_USUARIOS
			PRIMARY KEY (ID_CHAT)
);

DROP TABLE IF EXISTS MENSAJE;

CREATE TABLE MENSAJE (
	ID_MENSAJE				tinyint				NOT NULL,
    FECHA					date				NOT NULL,
	HORA					datetime			NOT NULL,
    ARCHIVO					blob				NOT NULL,
    FOTO					mediumblob			NOT NULL,
    RECEPTOR				tinyint				NOT NULL,
    EMISOR					tinyint				NOT NULL,
    CHAT_ALUM_PROF			tinyint				NOT NULL,
    CHAT_USUARIOS			tinyint				NOT NULL,

	CONSTRAINT PK_MENSAJE
			PRIMARY KEY (ID_MENSAJE),
	CONSTRAINT FK_MSJ_RECEPTOR
			FOREIGN KEY (RECEPTOR)
			REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FK_MSJ_EMISOR
			FOREIGN KEY (EMISOR)
			REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FK_MSJ_CHAT_ALUM_PROF
			FOREIGN KEY (CHAT_ALUM_PROF)
			REFERENCES CHAT_ALUMNO_PROFESOR(ID_ALUM_PROF),
	CONSTRAINT FK_MSJ_CHAT_USUARIOS
			FOREIGN KEY (CHAT_USUARIOS)
			REFERENCES CHAT_USUARIOS(ID_CHAT)

);

DROP TABLE IF EXISTS CATEGORIA;

CREATE TABLE CATEGORIA (
	ID_CATEGORIA				tinyint					NOT NULL,
    NOMBRE						VARCHAR(50)				NOT NULL,
	CREADOR						tinyint					NOT NULL,
    DESCRIPCION					VARCHAR(100)				NOT NULL,
    FECHA_CREACION				date				NOT NULL,
    HORA_CREACION				datetime				NOT NULL,

	CONSTRAINT PK_CATEGORIA
			PRIMARY KEY (ID_CATEGORIA),
	CONSTRAINT FK_CATEGORIA_CREADOR
			FOREIGN KEY (CREADOR)
			REFERENCES USUARIO(ID_USUARIO)
);

DROP TABLE IF EXISTS CURSO_CATEGORIA;

CREATE TABLE CURSO_CATEGORIA (
	ID_CURSO_CATEGORIA			tinyint			NOT NULL,
    CURSO						tinyint			NOT NULL,
	CATEGORIA					tinyint			NOT NULL,

	CONSTRAINT PK_CURSO_CATEGORIA
			PRIMARY KEY (ID_CURSO_CATEGORIA),
	CONSTRAINT FK_CURSO_CATEGORIA_CURSO
			FOREIGN KEY (CURSO)
			REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FK_CURSO_CATEGORIA_CATEGORIA
			FOREIGN KEY (CATEGORIA)
			REFERENCES USUARIO(ID_USUARIO)
            
);

             
            
            
            
            
            
            
            
            
            
            
            